### PR TITLE
Specify that the authentication type used is BASIC

### PR DESCRIPTION
**Pull request by PierrickVoulet**
This is to make sure the developer understands the meaning of the username and password fields on the Proxy settings page.

### CODE REVIEW

**Comment by PierrickVoulet** [comment]
The Japanese translation has not been updated because of my lack of knowledge (in Japanese language and how to convert to the right character encoding in the related properties files of the connector)

**Comment by laurentleseigneur** [comment]
LGTM

will try to find a Japanese translator

**Comment by NathalieC** [comment]
Taking the point to Akira.

**Comment by NathalieC** [comment]
Sent the email to Akira. Asked him to translate the following sentence : "Set the optional proxy settings; these can include BASIC authentication information." Are you positive this will not appear in Crowdin?

**Comment by PierrickVoulet** [comment]
From my understanding, the languages that are supported by the product are not open to translation (could someone confirm?)

**Comment by NathalieC** [comment]
Here is the translation : 
環境設定でオプションのプロキシを設定します。これで、Basic認証情報を含めることができます。for the string "Set the optional proxy settings; these can include BASIC authentication information."
I'll let you insert it in the relevant translation files.

**Comment by laurentleseigneur** [comment]
can you had it @PierrickVouletBonitasoft to this PR ?

**Comment by PierrickVoulet** [comment]
Done

**Pull request merged**
